<a href="https://colab.research.google.com/github/miguel7092/Miguel44.github.io/blob/main/El_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
lista = [1, 3, 6, 7, 12, 9]
lista

[1, 3, 6, 7, 12, 9]

Le agregamos el objeto arr al np.array(lista)

In [6]:
arr = np.array(lista)

In [7]:
type(arr)

numpy.ndarray

In [2]:
matriz =[[5, 3, 6],[8, 6, 9],[23, 11, 7]]
matriz = np.array(matriz)
matriz

array([[ 5,  3,  6],
       [ 8,  6,  9],
       [23, 11,  7]])

In [8]:
arr[0] + arr[2] + arr[4]

19

In [9]:
matriz[2,1]

11

In [10]:
arr[3:-1]

array([ 7, 12])

In [11]:
arr[1:3]

array([3, 6])

In [12]:
arr[0:3]

array([1, 3, 6])

In [13]:
arr[2:]

array([ 6,  7, 12,  9])

In [15]:
arr

array([ 1,  3,  6,  7, 12,  9])

In [14]:
arr[::2]

array([ 1,  6, 12])

In [16]:
arr[:3:]

array([1, 3, 6])

In [17]:
arr[:2:]

array([1, 3])

In [18]:
arr[:4:]

array([1, 3, 6, 7])

In [21]:
arr[:4]

array([1, 3, 6, 7])

In [22]:
arr[:4:2]

array([1, 6])

In [29]:
arr

array([ 1,  3,  6,  7, 12,  9])

In [28]:
arr[:-3:2]

array([1, 6])

En este array lo que se realizo primero es escoger el primer elemento cero que es 1 luego en -3 escogemos 1, 3, 6 y con un paso de 2 entonces 1 y 6.


In [27]:
arr[1:-2:2]

array([3, 7])

In [30]:
matriz

array([[ 5,  3,  6],
       [ 8,  6,  9],
       [23, 11,  7]])

In [31]:
matriz[:2,:2]

array([[5, 3],
       [8, 6]])

In [32]:
matriz[1:,:2]

array([[ 8,  6],
       [23, 11]])

In [34]:
arr

array([ 1,  3,  6,  7, 12,  9])

In [35]:
arr[: : 3]

array([1, 7])